"""
train_model.py — ML Training Pipeline
=======================================
HOW IT WORKS (plain English):
  1. Load the CSV generated by prep_data.py
  2. Split into train/test (80/20), stratified to preserve the 5% fraud ratio
  3. Build a preprocessing pipeline:
       - One-Hot Encode the 3 categorical columns (Provider, Diagnosis, Procedure)
         because ML models need numbers, not strings
       - Pass the numeric column (Total_Claim_Amount) through unchanged
  4. Apply SMOTE — Synthetic Minority Oversampling Technique:
       - Problem: with 5% fraud, the model sees 19 legit claims for every 1 fraud.
         It would just learn to always predict "legit" and be 95% accurate — useless.
       - SMOTE solution: creates NEW synthetic fraud samples by interpolating between
         existing fraud examples, balancing the training set to 50/50.
       - CRITICAL: SMOTE only runs during training, NEVER on test/inference data.
  5. Train a RandomForestClassifier (300 trees)
  6. Evaluate on held-out test set (ROC-AUC, precision, recall for fraud class)
  7. Save the entire pipeline as fraud_model.joblib

WHY RandomForest:
  - Naturally outputs probabilities (predict_proba) → perfect for risk scores
  - Works well with mixed data (after encoding)
  - Compatible with SHAP TreeExplainer for fast, exact explanations
  - Resistant to overfitting with enough trees

Run:
    python train_model.py
Output:
    fraud_model.joblib
"""

import joblib
import numpy as np
import pandas as pd

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline 

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

# ── Config ─────────────────────────────────────────────────────────────────────
CSV_PATH   = "synthetic_claims.csv"  # Kept original name
MODEL_PATH = "fraud_model.joblib"    # Kept original name
SEED       = 42

# ══════════════════════════════════════════════════════════════════════════════
# 1. Load data
# ══════════════════════════════════════════════════════════════════════════════
print(f"📂  Loading data from {CSV_PATH}...")
df = pd.read_csv(CSV_PATH)
print(f"    Shape: {df.shape}  |  Fraud rate: {df['Is_Fraud'].mean()*100:.1f}%")

CATEGORICAL_FEATURES = ["Provider_ID", "Diagnosis_Code", "Procedure_Code"]
NUMERIC_FEATURES     = ["Total_Claim_Amount"]
ALL_FEATURES         = CATEGORICAL_FEATURES + NUMERIC_FEATURES

X = df[ALL_FEATURES]
y = df["Is_Fraud"]

# ══════════════════════════════════════════════════════════════════════════════
# 2. Train/test split
# ══════════════════════════════════════════════════════════════════════════════
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=SEED,
    stratify=y,
)

# ══════════════════════════════════════════════════════════════════════════════
# 3. Preprocessing
# ══════════════════════════════════════════════════════════════════════════════
categorical_transformer = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", categorical_transformer, CATEGORICAL_FEATURES),
        ("num", "passthrough",           NUMERIC_FEATURES),
    ],
    remainder="drop",
)

# ══════════════════════════════════════════════════════════════════════════════
# 4. Pipeline with SMOTE
# ══════════════════════════════════════════════════════════════════════════════
# SMOTE helps balance the dataset so the model doesn't ignore the 5% fraud cases.

pipeline = ImbPipeline(steps=[
    ("preprocessor", preprocessor),
    ("smote", SMOTE(
        sampling_strategy="auto",
        random_state=SEED,
        k_neighbors=5,
    )),
    ("classifier", RandomForestClassifier(
        n_estimators=300,
        min_samples_leaf=2,
        class_weight="balanced",
        random_state=SEED,
        n_jobs=-1,
    )),
])

# ══════════════════════════════════════════════════════════════════════════════
# 5. Train & Evaluate
# ══════════════════════════════════════════════════════════════════════════════
print("\n🏋️  Training Pipeline (Random Forest + SMOTE)...")
pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)
y_prob = pipeline.predict_proba(X_test)[:, 1]

print("\n📊  Classification Report:")
print(classification_report(y_test, y_pred, target_names=["Legit", "Fraud"]))
print(f"    ROC-AUC: {roc_auc_score(y_test, y_prob):.4f}")

# ══════════════════════════════════════════════════════════════════════════════
# 6. Feature Importance
# ══════════════════════════════════════════════════════════════════════════════
rf         = pipeline.named_steps["classifier"]
ohe        = pipeline.named_steps["preprocessor"].named_transformers_["cat"]
ohe_names  = ohe.get_feature_names_out(CATEGORICAL_FEATURES).tolist()
feat_names = ohe_names + NUMERIC_FEATURES

importances = pd.Series(rf.feature_importances_, index=feat_names)
print("\n🔍  Top-10 Feature Importances:")
print(importances.nlargest(10).to_string())

# ══════════════════════════════════════════════════════════════════════════════
# 7. Save
# ══════════════════════════════════════════════════════════════════════════════
joblib.dump(pipeline, MODEL_PATH)
print(f"\n💾  Saved → {MODEL_PATH}")